### ISSUE TITLE
Modify default UI components and add TUL logos , fonts to header, footer and homepage

### ISSUE THREAD

**Issue by mrovnanik** [dataquest-dev/dspace-angular#188]
Components to start with:

@HuynhKhoa1601 Use logos, fonts stored on MS Teams storage (check MS Teams/TUL >>> Files)

**Comment by mrovnanik** [comment]
@milanmajchrak Milan, add list of components that Lock should start with

**Comment by milanmajchrak** [comment]
@HuynhKhoa1601 I will try to describe our FE deployment and some first steps what to do.

DSpace allows the user to customize UI by customizing theme of certain components, you can read more about it here: https://wiki.lyrasis.org/display/DSDOC7x/Upgrading+DSpace#UpgradingDSpace-UpgradingtheFrontend(UserInterface) **but** we do not customize UI by customizing these themes because not every component is possible to customize and we modified some components in the deep level, so it is impossible to customize some components by customizing them by the themes. I just wanted to tell you something about themes because it is recommended by the DSpace, but we updated DSpace in our way.

First step I'd like to ask you to do is:
- Update the home page, footer and header. Now the home page is modified in the component `home-page.component.html`. This home page is completely changed due to CLARIN requirements, but we want to have home page like in the Vanilla DSpace, so please just copy the home-page component from the Vanilla and replace our customized CLARIN-DSpace home-page and then update the colors, icons following the TUL design manual. (Update *.ts, *.scss, *.spec files also)
- Customize the footer and header this way - copy code from vanilla and update colors.

**Comment by HuynhKhoa1601** [comment]
thanks, I'll do it today

**Comment by milanmajchrak** [comment]
@HuynhKhoa1601 
Useful links:
**TUL**
- TUL (University of Liberec) actual running DSpace 6.3.: https://dspace.tul.cz/
- TUL home page: https://www.tul.cz/en/home-page/

**Vanilla**
- Vanilla UI demo: https://demo7.dspace.org/home
- Vanilla BE demo: https://api7.dspace.org/server/#/server/api

**Customized Vanilla**
- Examples of customized Vanilla DSpace (check `Site URL`): https://registry.lyrasis.org/?gv_search=7.x&filter_10=DSpace&filter_4_6&filter_3&filter_20&filter_28&mode=all

**Comment by milanmajchrak** [comment]
@HuynhKhoa1601 pages which should be customized:
- Item view: https://github.com/dataquest-dev/dspace-angular/issues/191
- Search page: https://github.com/dataquest-dev/dspace-angular/issues/192
- Home page: https://github.com/dataquest-dev/dspace-angular/issues/188

Components:
- Menu: https://github.com/dataquest-dev/dspace-angular/issues/198
- CitacePRO iframe: https://github.com/dataquest-dev/dspace-angular/issues/199

If you update these pages and global colors/fonts/.. in the whole project, the first phase of the customization should be done.

**Do not update:** these pages will be forbidden in the TUL customization
- `/licenses`
- `/handle-table`
