### ISSUE TITLE
TUL/after_test-5 Overview size doesn't match thumbnail box size

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#282]
## Problem description
![image](https://github.com/dataquest-dev/dspace-angular/assets/90026355/3ec6abd6-6633-40d1-8a29-53c12abddb03)

**Comment by milanmajchrak** [comment]
I've tried to reproduce this error and I cannot see this bad behavior. Steps:
1. Create Item with pdf file.
2. I run the command `dspace filter-media`

And the thumbnail size was correct.

**Comment by MajoBerger** [comment]
Part of the problem is old application of `filter-media` to content. When imported from old installation, the sizes are different and look bad in dspace 7. Using `dspace filter-media -f` reindexes even those files, therefore creating thumbnails of correct size. The only disadvantage is extra time, which is taken by reindexing ALL bitstream, as opposed to only indexing ones, that were not previously indexed.

**Comment by milanmajchrak** [comment]
> Part of the problem is old application of `filter-media` to content. When imported from old installation, the sizes are different and look bad in dspace 7. Using `dspace filter-media -f` reindexes even those files, therefore creating thumbnails of correct size. The only disadvantage is extra time, which is taken by reindexing ALL bitstream, as opposed to only indexing ones, that were not previously indexed.

Ok, so after reindexing all old application data using the `dspace filter-media -f` command this error should disappear.

**Comment by milanmajchrak** [comment]
We will check this behavior after reindexing all old application data.
