### ISSUE TITLE
internal/check deploys on dev5

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#318]
## Problem description
After dtq-dev are merged. 
Conflict file: https://github.com/dataquest-dev/dspace-angular/blob/customer/TUL/.github/workflows/erase_db.yml

**Comment by MajoBerger** [comment]
but this is not done @milanmajchrak

**Comment by MajoBerger** [comment]
@mrovnanik @milanmajchrak Currently there is only TUL dspace on dev-5 on port 86. Is that the desired state? Should there be dspace 7.5? or ONLY 7.5? I certainly do not recommend more than 2 deployments and perhaps it would be best to only have 1, since we want reporting stack to run there as well..

**Comment by MajoBerger** [comment]
I had to modify `/etc/hosts` of dspace-angular docker for TUL in order for it to be runnable in prod mode. Added IP of dev-5 eth interface in there under dev-5.pc and it worked

**Comment by MajoBerger** [comment]
Currently there are following dockers on dev-5:
nexus
certain parts of aston stack
dspace (port 86, TUL version)
dspace (port 85, clarin version)
DSpaces will still need some modification, because we did not pay attention on local deployments, when deploying to TUL and now it needs to be resolved. (Which I am trying to accomplish now)

Is this state alright? @mrovnanik @milanmajchrak

**Comment by milanmajchrak** [comment]
I suggest the clarin version

**Comment by MajoBerger** [comment]
This issue will continue here
https://github.com/dataquest-dev/dspace-angular/issues/348
Since there are still problems/imperfections with deployment. It needs bigger remake.
