### ISSUE TITLE
internal/logging in freezes on dev5

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#58]
### 1. Loading error
After I created an user/admin as administrator on the _dev5_ when I was logging with the new user/admin credentials the page just freezes in logging process with loading icon. In the console the FE throws error: 
![image](https://user-images.githubusercontent.com/90026355/178921052-a0d35bde-87c9-4b5c-bc46-f41a70097643.png)

I was trying to reproduce this error on local docker. I just built the dataquest docker images locally and tryied to create user as administrator. But the error doesn't occured, I successfuly logged in as the user. Then I built the dspace docker images to find out if the problem occurs in the official docker but it doesn't occurs either. That means there is problem with dev5.

**Comment by MajoBerger** [comment]
Solved, our nginx intercepted /info which disabled loading ~/info-info-module.js, then theme did not load, EULA did not load and user logged in for the first time (more specific, user which did not yet approve EULA) was stuck on loading EULA. Can be also fixed with patch rest call:
patch on epersons/eperson/uuid with content

[
  {
    "op": "add",
    "path": "/metadata/dspace.agreements.end-user",
    "value": [
      {
        "value": "true"
      }
    ]
  }
  
  or directly to database to table metadatafield, where metadata_field_id is 6, text_value is true, dspace_object_id is uuid of user and place must be 0.
